name: woland
version: 0.1.0
summary: Basic snap image for woland
description: Snap image
confinement: strict
base: core22
grade: stable
    
parts:   
  woland:
    source: .
    build-packages:
      - build-essential 
      - pkg-config
      - libavcodec-dev
      - libavutil-dev
      - libavformat-dev
      - libswscale-dev
    build-snaps:
      - go
    plugin: go
    override-build: | 
      go build -buildmode=c-shared -tags linux -o $SNAPCRAFT_PART_INSTALL/usr/lib/libwoland.so
    stage-packages: 
      - libglib2.0-0 
      - libglibc2.34 
      - libavcodec-dev
      - libavutil-dev
      - libavformat-dev
      - libswscale-dev